openapi: 3.0.0

securityDefinitions:
  bearerAuth:
    type: apiKey
    in: header
    name: Authorization
    description: Enter your bearer token in the format **Bearer &lt;token>**

security:
  - bearerAuth: []

paths:
# [GET] authors/all
  /author/all:
    get:
      security:
        - bearerAuth: [ ]
      summary: Find All Authors
      responses:
        '200':
          description: AuthorViewModel list
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: The author ID.
                  name:
                    type: string
                    description: The author name.
        '404':
          description: Not found

# [POST] author/create
  /author/create:
    post:
      security:
        - bearerAuth: [ ]
      summary: Add Author
      parameters:
        - in: body
          name: name
          schema:
            type: string
          required: true
          description: Author name
          example: '{"name": "Test Author"}'
      responses:
        '201':
          description: Author is created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: The author ID.
                  name:
                    type: string
                    description: The author name.
        '500':
          description: Server error


# [GET] poetry/all
  /poetry/all:
    get:
      security:
        - bearerAuth: [ ]
      summary: Find all poetry
      responses:
        '200':
          description: PoemViewModel list
          content:
            application/json:
              schema:
                type: object
                properties:
                  author:
                    type: string
                    description: The poem author name.
                  content:
                    type: string[]
                    description: Poem content.
                  title:
                    type: string
                    description: Poem title.
        '404':
          description: Not found

# [POST] poetry/haiku
  /poetry/haiku:
    post:
      security:
        - bearerAuth: [ ]
      summary: Generate new Haiku
      parameters:
        - in: body
          name: authorId
          schema:
            type: string
          required: true
          description: Author ID
          example: '{"authorId": 1}'
      responses:
        '201':
          description: A Poem is created
          content:
            application/json:
              schema:
                type: object
                properties:
                  author:
                    type: string
                    description: The poem author name.
                  content:
                    type: string[]
                    description: Poem content.
                  title:
                    type: string
                    description: Poem title.
        '500':
          description: Server error

  # [POST] poetry/limerick
  /poetry/limerick:
    post:
      security:
        - bearerAuth: [ ]
      summary: Generate new Limerick
      parameters:
        - in: body
          name: authorId
          schema:
            type: string
          required: true
          description: Author ID
          example: '{"authorId": 1}'
      responses:
        '201':
          description: A Poem is created
          content:
            application/json:
              schema:
                type: object
                properties:
                  author:
                    type: string
                    description: The poem author name.
                  content:
                    type: string[]
                    description: Poem content.
                  title:
                    type: string
                    description: Poem title.
        '500':
          description: Server error

# [DELETE] poetry/clear
  /poetry/clear:
    delete:
      security:
        - bearerAuth: [ ]
      summary: Clear all Poems and Authors, must be 'Administrator' role
      responses:
        '200':
          description: All Poems and Authors have been removed
        '500':
          description: Server error

schemes:
 - https
 - http
